// <auto-generated />
using System;
using BackBetha.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BackBetha.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220227145338_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackBetha.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ClientId"));

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BackBetha.Models.ClientSendingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("ClientSendingRecords");
                });

            modelBuilder.Entity("BackBetha.Models.Record", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AllowedRemaning")
                        .HasColumnType("integer");

                    b.Property<int?>("ClientSendingRecordId")
                        .HasColumnType("integer");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ClientSendingRecordId");

                    b.ToTable("Record");
                });

            modelBuilder.Entity("BackBetha.Models.Record", b =>
                {
                    b.HasOne("BackBetha.Models.ClientSendingRecord", null)
                        .WithMany("ClientRecords")
                        .HasForeignKey("ClientSendingRecordId");
                });

            modelBuilder.Entity("BackBetha.Models.ClientSendingRecord", b =>
                {
                    b.Navigation("ClientRecords");
                });
#pragma warning restore 612, 618
        }
    }
}
